<?
define ("_DOWNLOAD","Download");
define ("_HELP","Help");
define ("_TOP_NEW","Most recent files");
define ("_TOP_DOWNLOAD","Most downloaded files");
define ("_SEARCH","Search");
define ("_EXEC_SEARCH","Search");
define ("_ZIP_DIR","zip_dir");
define ("_SUBMIT_LINK","Submit link");
define ("_EXEC_SUBMIT_LINK","Submit link");
define ("_ADD_LINK","Add link");
define ("_EXEC_ADD_LINK","Add link");
define ("_SUBMIT_FILE","Submit file");
define ("_EXEC_SUBMIT_FILE","Submit file");
define ("_UPDATE_FILE","Cut file");
define ("_DELETE_SUBMITFILE","Delete file");
define ("_EXEC_DELETE_SUBMITFILE","Delete file");
define ("_EXEC_CUT_FILE","Cut file");
define ("_ADD_FILE","Add file");
define ("_EXEC_ADD_FILE","Add file");
define ("_RENAME_FILE","Rename file");
define ("_EXEC_RENAME_FILE","Modify file");
define ("_DELETE_FILE","Delete file");
define ("_EXEC_DELETE_FILE","Delete file");
define ("_ADD_DIR","Add directory");
define ("_EXEC_ADD_DIR","Add directory");
define ("_RENAME_DIR","Rename directory");
define ("_EXEC_RENAME_DIR","Rename directory");
define ("_DELETE_DIR","Delete directory");
define ("_EXEC_DELETE_DIR","Delete directory");
define ("_CUT_FILE","Cut file");

define ("_ANNULLA","Cancel");
define ("_MODIFICA_FILE","Modify file");
define ("_NUOVO_NOME_FILE","New file name");
define ("_NOME_FILE","Name:");
define ("_UPLOAD_DIRECTORY","Upload directory:");
define ("_TIPO_FILE","Type:");
define ("_SIZE_FILE","Size:");
define ("_DESCRIPTION","Description:");
define ("_RILASCIO","Released:");
define ("_DATE_UPLOAD","Date:");
define ("_CONTINUA","Continue");
define ("_DESCRIZIONE_FILE","File description");
define ("_SPOSTA_FILE","Move the file");
define ("_SPOSTA","Move");
define ("_FILE_SPOSTATO","File Moved");
define ("_CANCELLA_FILE","Delete file");
define ("_ELIMINA","Erase");
define ("_FILE_MODIFIED","File modified ");
define ("_FILE_DELETED","File deleted ");

define ("_SUBMIT_FILE","Submit file");
define ("_UPDATE_FILES","Files moved");
define ("_GREETING_UPDATE","Uploaded file will be evaluated as soon as possible.<br> Thanks for your contribution!<br>\n");
define ("_UPDATEBY","Submitted by: ");
define ("_VERSION","Version: ");
define ("_PREVIEW","Preview: ");
define ("_DELETEPREVIEW","Delete preview");
define ("_SUBMITTEDFILES","Submitted files ");
define ("_FILE_ACCEPTED","File moved in current folder ");
define ("_IN_FILE","Situed in: ");


define ("_ADD_FILE","Add file");
define ("_INVIA_FILE","Send file:");
define ("_UPFILE","Submit file!");
define ("_NEWFILE","New file:");
define ("_DESC_FILE","File description:");
define ("_FILE_VALIDO","File is valid and successfully sended!<hr> Some infos about it: \n");
define ("_FILE_VALIDO_UP","File sended!\n");
define ("_FILE_NON_VALIDO","Warning: file is not valid and not successfully sended!<br> Some infos about it: \n");
define ("_FILE_NON_VALIDO_UP","File not sended!\n");
define ("_ERRORE_DI_AUTENTICAZIONE","Autentication error:\n");

define ("_ADD_DIR","Create directory");
define ("_NOME_DIR","Directory name:");
define ("_DESC_DIR","Directory description:");
define ("_DIR_ADDED","Directory added");

define ("_RINOMINA_DIR","Rename directory");
define ("_NUOVO_NOME_DIR","New directory name:");
define ("_DIR_RENAMED","Directory renamed");
define ("_DIR_CUTTED","Directory cutted");
define ("_DIR_UPDATED","Directory pasted");


define ("_CANCELLA_DIR","Delete directory");
define ("_DIR_DELETED","Directory deleted");
define ("_IN","Situed in: ");
define ("DIR_IN","Warning: the directory situed in ");
define ("NOT_EMPTY","is not empty!");



define ("_FINDFILES","Find");
define ("_FINDINGFILES","Finding files");
define ("_FINDINGFILES_UP","Search");
define ("_NEW_SEARCH","New search");

define ("_TOPNEW","Recent files");
define ("_TOPDOWNLOAD","Top downloads");

define ("_REN","Modify");
define ("_CUT","Cut");
define ("_DEL","Delete");
define ("_PUT_DOWN","Put down");
define ("_ADD_DIR_ADMIN","Add directory");
define ("_ADD_FILE_ADMIN","Add file");
define ("_FN_MANAGER","Files - the FlatNuke file manager");
define ("_FN_REG","User registered");
define ("_FN_UNREG","User not registered");


define ("_NOME_LINK","Link name:");
define ("_INVIA_LINK","Send link:");
define ("_DESC_LINK","Link description: ");
define ("_SUBMIT_LINK","Submit link");
define ("_FILE_REMOTO","Link");
define ("_ADD_LINK","Add link");
define ("_NUOVO_FILE_LINK","New link:");
define ("_UPLINK","Submit remote file!");
define ("_ADD_LINK_ADMIN","Add remote file!");

define ("_NOME_LINK_RADIO","Name Radio:");
define ("_INVIA_LINK_RADIO","Insert Code Embedded Radio:");
define ("_NOME_LINK_EMBED","Name Embed:");
define ("_INVIA_LINK_EMBED","Insert Code Embedded:");


define ("_HELP_TXT","
<div class='help'>
<img src='applications/$appname/images/system-help.png' border='0' WIDTH='42' HEIGHT='42' alt='&#187;'><font class='blue_big'>Files - the File Manager </font>
<hr>
<font class='blue_big'>Presentation </font><br><br>
Welcome to Files: the Your File Manager<br />
This module is free software and is released under GPL license <br />
You may download, use, modify or copy it to your friends.
<hr>
<font class='blue_big'>User instructions </font><br><br>
<font class='red_bold'>Navigation and download</font><br>
By clicking a folder you have the access to his contents.
The current path is visible in <font class='black_bold'>Location</font> on module upper side. By clicking a path element you go back to the folder tree. By clicking the link &nbsp;<img src='applications/$appname/none_images/mini_down.gif' border='0' alt='&#187;'>&nbsp;<font class='black_bold'>Download directory </font> under the folder, you can download its contents as unique compressed file in zip format. By clicking the name of a file or the &nbsp;<img src='applications/$appname/none_images/mini_down.gif' border='0' alt='&#187;'>&nbsp;<font class='black_bold'>Download</font> link, you start to download it. New or recently updated files are evidenced by the icon&nbsp;<img src='applications/$appname/none_images/new.gif' border='0' alt='New!'>. Foldes showing New icon beside, contain newer or updated file inside their directory tree.  <br>
With the increasing of files number on site, can become quite complicated to find those you are looking for.
You can search for a specific file by clicking the <img src='applications/$appname/none_images/icon2.gif' border='0' alt='&#187;'> <font class='black'>[Find]</font> link and
by writing a word inside the input line of the search module. By clicking the <font class='black_bold'>Find</font> button, the word  you wrote will be searched in files names and in their descriptions.
The found files list will  be shown.<br>
<font class='black_bold'>Most downloaded files</font> show you the updated list of the 20 most downloaded files.<br>
<font class='black_bold'>Most recent files</font> show you the roster of the 20 most recent files uploaded or updated on section.
<hr>
<font class='blue_big'>Registered user instructions </font><br><br>
<font class='red_bold'>Submit files</font><br />
If you are a registered user you can submit your files for download. To do so you must use the &nbsp;<img src='applications/$appname/none_images/mini_up.gif' border='0' alt='&#187;'>&nbsp;<font class='black'>[Submit file!] </font> link in the upper side of module. A form will help you to choose the file to submit from your hard disk. You can specify file description by filling appropriate field.<br>
Your submitted files will be evaluated by site administrator who will decide if he can make them available for download. Warning, may be some limitation on file size.<br>
You can submit remote file too by clicking the <img src='applications/$appname/none_images/mini_up.gif' border='0' alt='&#187;'>&nbsp;<font class='black'>[Submit remote file!]</font> link.

<hr>
<font class='blue_big'>Administrators instructions </font><br><br>
<font class='red_bold'>Upload files</font><br />
If you are the site administrator, you can create new folders by clicking &nbsp;<img src='applications/$appname/none_images/mini_up.gif' border='0' alt='&#187;'>&nbsp;<font class='black'>[Add directory]</font>
and upload files to the server with &nbsp;<img src='applications/$appname/none_images/mini_up.gif' border='0' alt='&#187;'>&nbsp;<font class='black'>[Add file]</font> and <img src='applications/$appname/none_images/mini_up.gif' border='0' alt='&#187;'>&nbsp;<font class='black'>[Add remote file]</font> you find in the module upper side.
Forms will help you to create folders and upload files by specifying name and description.
Warning, in some case it is not possible to send files exceeding determinate size with the browser. You will find a workaround later in this document.<br><br />
<font class='red_bold'>Delete files</font><br />
Browsing the directory tree as administrator, you can delete files and folders by clicking the link <font class='red'>[Delete]</font> on their bottom side. You will be asked to confirm the operation. Be aware that the folders must be empty to be deleted.<br><br />
<font class='red_bold'>Move files</font><br />
Sometimes it would be necessary to move files from a folder to another one. This operation is executed per a sort of 'cut and paste' procedure. Click &nbsp;<font class='red'>[Cut]</font> link bottom side the file you want to move, it will be 'cut' from folder and moved to <font class='black_bold'>CLIPBOARD</font> space, now you may to browse directory tree and to decide where 'paste' the file down by clicking the &nbsp;<font class='red'>[Put down]</font> link. <br><br />
<font class='red_bold'>Rename files and modify descriptions</font><br />
As administrator you can rename files and folders by the &nbsp;<font class='red'>[Rename]</font> link you find at their bottom side.  A form - that has to be filled  in order to change the file name and/or description - will be shown.<br><br />
<font class='red_bold'>Submitted Files</font><br />
In <font class='black_bold'>Submitted files section</font> users submitted files are listed. After the evaluation you can authorize submitted files, so they will be available for download, by clicking the &nbsp;<font class='red'>[Put down]</font> link or you can delete them by the &nbsp;<font class='red'>[Delete]</font> link.<br><br />
<font class='red_bold'>Upload of exceeding limits files</font><br />
Sometimes it is not possible to send files exceeding determinate size cause server or browser limitations. In this case you need an FTP client to copy your files to the server inside the  flatnuke/applications/Files/none_updatedir folder. As administrator you will be able to see your file listed in <font class='black_bold'>Uploades files waiting confirmation</font> section, you can insert them in current folder by clicking &nbsp;<font class='red'>[Put down]</font> link that you find on their bottom side.<br>
System will try to delete uploaded files from none_updatedir folder as soon as they are copied to their destination. In case the server deny delete operation, you have to delete the files by hands with the FTP client.
<hr>
&nbsp;&nbsp;<font class='blue_big'>Authors</font><br><br>
<a href='mailto:__vroby__@libero.it'>__vroby__</a><font class='blue'>&nbsp;&nbsp;Ideation and coding.</font> <br/>
<!-- <a href='mailto:zoiba@libero.it'>&nbsp;&nbsp;&nbsp;&nbsp;zoiba</a><font class='blue'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graphics, suggestions and help documentation.</font><br/> -->
<!-- <a href='http://winpenpack.com'>&nbsp;&nbsp;&nbsp;&nbsp;Danix</a> <font class='blue'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Restyling grafico, testing e suggerimenti</font><br/> -->
<a href='mailto:deplano.d@gmail.com'>&nbsp;&nbsp;Daniele</a> <font class='blue'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Code Modify, Graphics Restyling, testing</font><br/>
<hr></div>
");
?>

