<?
define ("_DOWNLOAD","Download");
define ("_HELP","Help");
define ("_TOP_NEW","Elenco nuovi files");
define ("_TOP_DOWNLOAD","Files più scaricati");
define ("_SEARCH","Cerca");
define ("_EXEC_SEARCH","Cerca");
define ("_ZIP_DIR","zip_dir");
define ("_SUBMIT_LINK","Proponi link");
define ("_EXEC_SUBMIT_LINK","Proponi link");
define ("_ADD_LINK","Inserisci link");
define ("_EXEC_ADD_LINK","Inserisci link");
define ("_SUBMIT_FILE","Proponi file");
define ("_EXEC_SUBMIT_FILE","Proponi file");
define ("_UPDATE_FILE","Sposta file");
define ("_DELETE_SUBMITFILE","Cancella file");
define ("_EXEC_DELETE_SUBMITFILE","Cancella file");
define ("_EXEC_CUT_FILE","Taglia file");
define ("_ADD_FILE","Inserisci file");
define ("_EXEC_ADD_FILE","Inserisci file");
define ("_RENAME_FILE","Rinomina file");
define ("_EXEC_RENAME_FILE","Modifica file");
define ("_DELETE_FILE","Cancella file");
define ("_EXEC_DELETE_FILE","Cancella file");
define ("_ADD_DIR","Crea directory");
define ("_EXEC_ADD_DIR","Crea directory");
define ("_CUT_DIR","Taglia directory");
define ("_EXEC_CUT_DIR","Taglia directory");
define ("_RENAME_DIR","Rinomina directory");
define ("_EXEC_RENAME_DIR","Rinomina directory");
define ("_DELETE_DIR","Cancella directory");
define ("_EXEC_DELETE_DIR","Cancella directory");
define ("_CUT_FILE","Taglia file");


define ("_ANNULLA","Annulla");
define ("_MODIFICA_FILE","Modifica file");
define ("_NUOVO_NOME_FILE","Nuovo nome file:");
define ("_UPLOAD_DIRECTORY","Directory di upload:");
define ("_TIPO_FILE","Tipo:");
define ("_NOME_FILE","Nome:");
define ("_SIZE_FILE","Dimensione:");
define ("_DESCRIPTION","Descrizione:");
define ("_RILASCIO","Data rilascio:");
define ("_DATE_UPLOAD","Data:");
define ("_CONTINUA","Continua");
define ("_DESCRIZIONE_FILE","Descrizione file");
define ("_SPOSTA_FILE","Sposta il file");
define ("_SPOSTA","Sposta");
define ("_FILE_SPOSTATO","File spostato");
define ("_CANCELLA_FILE","Cancella il file");
define ("_ELIMINA","Elimina");
define ("_FILE_MODIFIED","File modificato");
define ("_FILE_DELETED","File cancellato");


define ("_SUBMIT_FILE","Proponi file");
define ("_UPDATE_FILES"," Files spostati");
define ("_GREETING_UPDATE","Il file proposto verrà esaminato al più presto! <br>Grazie per averlo inviato!<br>\n");
define ("_UPDATEBY","Proposto da: ");
define ("_VERSION","Versione: ");
define ("_PREVIEW","Anteprima: ");
define ("_DELETEPREVIEW","Cancella anteprima ");
define ("_SUBMITTEDFILES","Files proposti ");
define ("_FILE_ACCEPTED","File inserito nella cartella corrente ");
define ("_IN_FILE","Situato in: ");


define ("_ADD_FILE","Carica file");
define ("_INVIA_FILE","Invia file:");
define ("_UPFILE","Invia file!");
define ("_NEWFILE","Nuovo file:");
define ("_DESC_FILE","Descrizione:");
define ("_FILE_VALIDO","Il file è valido ed è stato inviato con successo!<br>Alcune informazioni sul file inviato:\n");
define ("_FILE_VALIDO_UP","Invio riuscito!\n");
define ("_FILE_NON_VALIDO","Attenzione: il file non è valido e non è stato inviato con successo!<br> Alcune informazioni:\n");
define ("_FILE_NON_VALIDO_UP","Invio non riuscito!\n");

define ("_ERRORE_DI_AUTENTICAZIONE","Errore di autenticazione:\n");

define ("_ADD_DIR","Crea directory");
define ("_NOME_DIR","Nome directory:");
define ("_DESC_DIR","Descrizione:");
define ("_DIR_ADDED","Directory creata");
define ("_DIR_CUTTED","Directory tagliata");
define ("_DIR_UPDATED","Directory incollata");


define ("_RINOMINA_DIR","Rinomina directory");
define ("_NUOVO_NOME_DIR","Nuovo nome directory:");
define ("_DIR_RENAMED","Directory rinominata");

define ("_CANCELLA_DIR","Cancella directory");
define ("_CANCELLA_TREE","Cancella albero directory");
define ("_DIR_DELETED","Directory cancellata");
define ("_IN","Situata in: ");
define ("_DIR_IN","Attenzione: la directory situata in ");
define ("_NOT_EMPTY","non è vuota!");


define ("_FINDFILES","Cerca");
define ("_FINDINGFILES","Ricerca di ");
define ("_FINDINGFILES_UP","Cerca");
define ("_NEW_SEARCH","Nuova ricerca");


define ("_TOPDOWNLOAD","Piu' scaricati");
define ("_TOPNEW","Nuovi files");

define ("_REN","Modifica");
define ("_CUT","Taglia");
define ("_DEL","Elimina");
define ("_PUT_DOWN","Inserisci");
define ("_ADD_DIR_ADMIN","Aggiungi directory");
define ("_ADD_FILE_ADMIN","Aggiungi file");
define ("_FN_MANAGER","Files - il file manager di Flatnuke");
define ("_FN_REG","Utente registrato");
define ("_FN_UNREG","Utente non registrato");


define ("_NOME_LINK","Nome link:");
define ("_INVIA_LINK","Inserisci link:");
define ("_DESC_LINK","Descrizione link: ");
define ("_SUBMIT_LINK","Proponi file remoto");
define ("_FILE_REMOTO","File remoto");
define ("_ADD_LINK","Inserisci link");
define ("_NUOVO_FILE_LINK","Nuovo link:");
define ("_UPLINK","Invia file remoto!");
define ("_ADD_LINK_ADMIN","Inserisci file remoto");

define ("_NOME_LINK_RADIO","Nome Radio:");
define ("_INVIA_LINK_RADIO","Inserisci Codice Embedded Radio:");
define ("_NOME_LINK_EMBED","Nome Embed:");
define ("_INVIA_LINK_EMBED","Inserisci Codice Embedded:");


define ("_HELP_TXT","

<div class='help'><br>
<br>
<br>
<br>
<img src='../../applications/$appname/images/system-help.png' alt='»' border='0' height='42' width='42'><font class='blue_big'>Libre Office Web</font>
<hr><font class='blue_big'>Presentazione </font><br><br>
Benvenuto in Files: il nostro File Manager<br>
Questo modulo e' software libero sottoposto alla licenza GPL <br>
Puoi scaricarlo, usarlo, modificarlo e farne copie per i tuoi amici.
<hr><font class='blue_big'>Istruzioni per gli utenti </font><br>
<br>
<font class='red_bold'>Navigazione e download</font><br>
<br>
Nella barra principale si trovano i seguenti bottoni:<br>
Bottone <img src='../../applications/$appname/images/menu.png' alt='»' border='0' height='42' width='42'> apre e chiude il menu laterale sinistro;<br>
Bottone <img src='../../applications/$appname/images/files3.png' alt='»' border='0' height='42' width='42'> ricarica la pagina principale (Home) di Files3;<br>
Bottone <img src='../../applications/$appname/images/previous.png' alt='»' border='0' height='42' width='42'> <font class='black'>[Back]</font> per tornare indietro;<br>
Bottone con Avatar/Foto utente <img src='../../applications/$appname/libs/avatars/hack-daniel.png' alt='»' border='0' height='42' width='42'> che permette di andare al centro dei servizi di D+ Plus.<br>
<hr>
<br>
Sulla parte superiore del modulo, dopo la barra superiore, al centro e' sempre visibile un bottone <img src='../../applications/$appname/images/navigation.png' alt='»' border='0' height='42' width='42'>che permette di visionare il percorso corrente. Cliccando un elemento che compone il percorso risali l'albero delle cartelle.<br>
<br>
Cliccando sul una bottone cartella <img src='../../applications/$appname/images/folder.png' alt='»' border='0' height='42' width='42'> aprirai un'interfaccia che ti consentira' di scaricare la <font class='black_bold'> cartella/directory </font> con tutto il contenuto come unico file compresso in formato zip.<br>
Cliccando il nome di un file o sul link &nbsp;<img src='../../applications/$appname/none_images/mini_down.gif' alt='»' border='0'>&nbsp;<font class='black_bold'>Download</font> ne effettui il download. Files nuovi o recentemente aggiornati sono evidenziati dall'icona&nbsp;<img src='../../applications/$appname/none_images/new.gif' alt='New!' border='0'>. Le cartelle che mostrano quest'icona al loro fianco contengono files nuovi o aggiornati all'interno del loro sotto-albero.<br>
Con l'aumentare dei files disponibili sul sito, puo' diventare complicato trovare quelli desiderati.
Puoi effetuare una ricerca dei file presenti utilizzando il link <img src='../../applications/$appname/none_images/icon2.gif' alt='»' border='0'> <font class='black'>[Cerca]</font> e scrivendo una o più parole nella riga di immissione testo del modulo di ricerca.
Cliccando sul pulsante <font class='black_bold'>Cerca</font>, la parola inserita verra' cercata nei nomi dei files e nelle loro descrizioni. Comparira' pertanto la lista dei files trovati.<br>
Il link <font class='black_bold'>File più scaricati</font> mostra la lista aggiornata dei 20 files maggiormente scaricati.<br>
Il link <font class='black_bold'>Elenco nuovi files</font> mostra l'elenco dei files inseriti o aggiornati recentemente.<br>
<br>
E' possibile inserire files remoti utilizzando l'apposito link <img src='../../applications/$appname/none_images/mini_up.gif' alt='»' border='0'>&nbsp;<font class='black'>[Invia file remoto!].</font><br>
<br>
<font class='red_bold'>Caricare files</font><br>
Se sei uno degli utenti registrati del sito, hai la possibilita' di
creare nuove cartelle cliccando sul link &nbsp;<img src='../../applications/$appname/none_images/mini_up.gif' alt='»' border='0'>&nbsp;<font class='black'>[Aggiungi directory]</font> e inviare files al server con &nbsp;<img src='../../applications/$appname/none_images/mini_up.gif' alt='»' border='0'>&nbsp;<font class='black'>[Aggiungi file]</font> e <img src='../../applications/$appname/none_images/mini_up.gif' alt='»' border='0'>&nbsp;<font class='black'>[Aggiungi file remoto]</font> che trovi nella parte superiore del modulo. Le operazioni di creazione cartelle e di caricamento dei files avvengono tramite dei modulo che ti permettono di specificarne il nome e descrizione. Attenzione, in alcuni casi non e' possibile inviare tramite il browser dei files che superino un certo peso. Piu' avanti verra' spiegato come caricare files che eccedono tale limite.<br>
<br>
<font class='red_bold'>Cancellare files</font><br>
Navigando l'albero delle cartelle, puoi cancellare un file o una cartella cliccando il link &nbsp;<font class='red'>[Elimina]</font> sotto il nome dell'elemento stesso. Ti sara' chiesto se procedere con l'operazione. Ricorda che una cartella deve essere vuota per poter essere cancellata.<br>
<br>
<font class='red_bold'>Spostare files</font><br>
A volte puo' essere necessario spostare determinati file da una cartella ad un altra. Questa operazione viene eseguita tramite una sorta di 'copia e incolla'. Cliccando il link &nbsp;<font class='red'>[Taglia]</font> che trovi sotto un file questo viene 'tagliato' e spostato in &nbsp;<font class='black_bold'>CLIPBOARD</font>, puoi così navigare l'albero delle cartelle e decidere dove andare ad 'incollarlo' tramite il link &nbsp;<font class='red'>[Inserisci]</font>.<br>
<br>
<font class='red_bold'>Rinominare e modificare descrizione files</font><br>
Come utente registrato puoi anche rinominare un file o una cartella di tua proprietà cliccando il link &nbsp;<font class='red'>[Rinomina]</font> che trovi al di sotto del suo nome. Ti sara' proposto un modulo col quale cambiare il nome e/o la descrizione.<br>
<br>
<font class='red_bold'>Caricamento files che eccedono il limite</font><br>
In alcuni casi non e' possibile inviare files oltre un certo limite di dimensioni causa limitazioni del server o del brower. Il limite di grandezza per ogni file è fissato in un massimo di 25Mb.<br>
<hr>
&nbsp;&nbsp;<font class='blue_big'>Autori</font><br>
<br>
<a href='mailto:vroby.mail@gmail.com'>__vroby__</a> <font class='blue'>&nbsp;&nbsp;Ideazione e codice originario.</font> <br>
<!-- <a href='mailto:zoiba@libero.it'>&nbsp;&nbsp;&nbsp;&nbsp;zoiba</a> <font class='blue'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Grafica, suggerimenti ed istruzioni</font><br/> -->
<!-- <a href='http://winpenpack.com'>&nbsp;&nbsp;&nbsp;&nbsp;Danix</a> <font class='blue'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Restyling grafico, testing e suggerimenti</font><br/> --><a
href='mailto:deplano.d@gmail.com'>&nbsp;&nbsp;Daniele</a> <font class='blue'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Modifiche Codice, Funzioni Aggiuntive, Restyling grafico, testing</font><br>
<hr></div>
");
?>

