<?php

define("_USER","Utente");

define("_DATA_REG","Data Registrazione");
define("_LAST_ACCES","Ultimo Accesso");

define("_NOME","Nome");
define("_EMAIL","Email");
define("_SITO_WEB","Sito WEB");
define("_PROFESSIONE","Professione");
define("_PROVENIENZA","Provenienza");
define("_AVATAR","Avatar");
define("_IMMAGINE_URL","Immagine URL");
define("_FIRMA","Firma");
define("_THEME","Theme");


define("_VIEWUSER","Visualizza utente");
define("_GRUPPI","Gruppi di appartenenza");




?>
